title: .vijayjain
url: "https://github.com/vjain89/me"
baseurl: "/me"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/vjain89"
# footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/about"
 - name: "Portfolio"
   link: "/portfolio"
 - name: "Contact"
   link: "/contact"
